# Generated by Django 4.0.2 on 2022-02-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0003_rename_users_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=264),
        ),
    ]
