# Generated by Django 4.0.2 on 2022-02-15 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Signin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
